# -*- coding: utf-8 -*-
"""Language Translation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GsV5BPEFd3p0s2pYeWvlK9AhKAWVbaOL
"""

! pip install sentencepiece

!pip freeze | grep transformers

from transformers import MBartForConditionalGeneration, MBart50TokenizerFast

model = MBartForConditionalGeneration.from_pretrained("facebook/mbart-large-50-one-to-many-mmt")

tokenizer = MBart50TokenizerFast.from_pretrained("facebook/mbart-large-50-one-to-many-mmt", src_lang="en_XX")

article_en = "this is laptop"

model_inputs = tokenizer(article_en, return_tensors="pt")

generated_tokens = model.generate(
    **model_inputs,
    forced_bos_token_id=tokenizer.lang_code_to_id["hi_IN"]
)

translation = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)

translation